apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator3
  namespace: openshift-operators
spec:
  channel: stable
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
  name: servicemeshoperator3
  source: redhat-operators
  sourceNamespace: openshift-marketplace