apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- cluster-namespace-rhb-apicurio-registry-operator.yaml
- rhb-apicurio-registry-operator-operatorgroup-rhb-apicurio-registry-operator.yaml
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: rhb-apicurio-registry-operator
  target:
    kind: Subscription
    name: apicurio-registry
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: rhb-apicurio-registry-operator
  target:
    kind: ConfigMap
    name: cluster-versions
