apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- cluster-namespace-openshift-vertical-pod-autoscaler.yaml
- openshift-vertical-pod-autoscaler-operatorgroup-vertical-pod-autoscaler.yaml
- openshift-vertical-pod-autoscaler-subscription-vertical-pod-autoscaler.yaml
- openshift-vertical-pod-autoscaler-verticalpodautoscalercontroller-default.yaml
replacements:
- source:
    fieldPath: data.vertical-pod-autoscaler
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: vertical-pod-autoscaler
