apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: patch-console-pipelines-plugin
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: patch-console-pipelines-plugin
    spec:
      containers:
        - name: patch-console
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e
              echo "Ensuring pipelines-console-plugin is in Console plugins list..."
              if ! oc get console.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' | grep -qw "pipelines-console-plugin"; then
                echo "Adding pipelines-console-plugin to Console..."
                oc patch console.operator.openshift.io cluster --type=json -p='[{"op": "add", "path": "/spec/plugins/-", "value": "pipelines-console-plugin"}]'
                echo "✅ Plugin pipelines-console-plugin added."
              else
                echo "✅ Plugin pipelines-console-plugin already present."
              fi
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
