apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- cluster-namespace-keycloak.yaml
- keycloak-operatorgroup-rhbk-operator.yaml
- keycloak-subscription-rhbk-operator.yaml
replacements:
- source:
    fieldPath: data.rhbk-operator
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: rhbk-operator
