apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - cluster-namespace-keycloak.yaml
  - keycloak-operatorgroup-rhbk-operator.yaml
  - keycloak-subscription-rhbk-operator.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.rhbk-operator
    targets:
      - select:
          kind: Subscription
          name: rhbk-operator
        fieldPaths:
          - spec.channel
