kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-clusterautoscaler
rules:
  - verbs:
      - '*'
    apiGroups:
      - autoscaling.openshift.io
    resources:
      - '*'
