apiVersion: autoscaling.openshift.io/v1
kind: ClusterAutoscaler
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: default
spec:
  resourceLimits:
    gpus:
    - type: nvidia
      min: 0
      max: 8
  scaleDown:
    delayAfterAdd: 20m
    enabled: true