apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-clusterautoscaler-default.yaml
  - cluster-clusterrole-edit-clusterautoscaler.yaml
  - cluster-crb-autoscaler-clusterautoscaler-edit.yaml
  - openshift-gitops-configmap-machineautoscaler.yaml 
  - openshift-gitops-job-create-gpu-machineset.yaml
