apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- cluster-namespace-rhb-apicurio-registry-operator.yaml
- rhb-apicurio-registry-operator-operatorgroup-rhb-apicurio-registry-operator.yaml
- rhb-apicurio-registry-operator-subscription-rhb-apicurio-registry-operator.yaml
replacements:
- source:
    fieldPath: data.rhb-apicurio-registry
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: rhb-apicurio-registry-operator
