apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- openshift-operators-subscription-apicurio-registry.yaml
replacements:
- source:
    fieldPath: data.rhbar
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: apicurio-registry
