apiVersion: v1
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type-protocol: oci
    opendatahub.io/connection-type-ref: oci-v1
    openshift.io/display-name: Red Hat Registry
  labels:
    opendatahub.io/dashboard: "true"
  name: registry-redhat-io
  namespace: ai-models-service
type: Opaque
data:
  OCI_HOST: cmVnaXN0cnkucmVkaGF0Lmlv
