apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: granite-llm-sa
  name: granite-llm-sa-token
  namespace: ai-models-service
type: kubernetes.io/service-account-token
