apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-pipeline-access
  namespace: ai-models-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inferenceservice-user
subjects:
- kind: ServiceAccount
  name: default
  namespace: ai-generation-llm-rag
- kind: ServiceAccount
  name: pipeline-runner-pipelines
  namespace: ai-generation-llm-rag
