apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/sync-options: Force=true
  name: disable-pipelines-console-plugin
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: disable-pipelines-console-plugin
    spec:
      containers:
        - name: disable-console-plugin
          image: quay.io/devfile/universal-developer-image:ubi8-latest 
          command:
            - /bin/bash
            - -c
            - |
              set -e
              if [[ -n $(oc get console.operator.openshift.io cluster -o yaml | yq '.spec.plugins[] | select(. == "pipelines-console-plugin")') ]]; then
                echo "Plugin pipelines-console-plugin exists. Disable it..."
                PLUGIN_INDEX=$(oc get console.operator.openshift.io cluster -o yaml | yq '.spec.plugins | to_entries | .[] | select(.value == "pipelines-console-plugin") | .key')
                oc patch console.operator.openshift.io cluster --type=json -p="[{'op': 'remove', 'path': '/spec/plugins/$PLUGIN_INDEX'}]"
                echo "Plugin pipelines-console-plugin successfully removed"
              else
                echo "Plugin pipelines-console-plugin not found. Nothing to delete."
              fi
      restartPolicy: OnFailure
      serviceAccountName: openshift-gitops-argocd-application-controller
