apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: latest
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
