# Temporary fix for issue: 
#    https://issues.redhat.com/browse/SRVKP-7859
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: regenerate-certficates-tekton-results
  namespace: openshift-gitops
spec:
  template:
    metadata:
      labels:
        app: hack-tekton-results
    spec:
      containers:
      - name: tekton-results-hack
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e

          INGRESS_NAME="ingress"
          INGRESS_NS="openshift-ingress"
          SECRET_NAME="tekton-results-tls"
          DEPLOYMENT_NAME="tekton-results-api"

          echo "INFO: Waiting for Certificate ${INGRESS_NAME} in ${INGRESS_NS} to be Ready..."
          while true; do
            READY=$(oc get certificate ${INGRESS_NAME} -n ${INGRESS_NS} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' 2>/dev/null || true)
            if [ "$READY" = "True" ]; then
              echo "INFO: Certificate ${INGRESS_NAME} is Ready."
              break
            else
              echo "INFO: Certificate ${INGRESS_NAME} not Ready yet, retrying in 10 seconds..."
              sleep 10
            fi
          done

          echo "INFO: Deleting secret ${SECRET_NAME} in openshift-pipelines..."
          oc delete secret ${SECRET_NAME} -n openshift-pipelines >/dev/null 2>&1 || true

          echo "INFO: Waiting for secret ${SECRET_NAME} in openshift-pipelines to be recreated..."
          while true; do
            if oc get secret ${SECRET_NAME} -n openshift-pipelines >/dev/null 2>&1; then
              echo "INFO: Secret ${SECRET_NAME} recreated."
              break
            else
              echo "INFO: Secret ${SECRET_NAME} not recreated yet, retrying in 10 seconds..."
              sleep 10
            fi
          done

          echo "INFO: Scaling deployment ${DEPLOYMENT_NAME} in openshift-pipelines to 0..."
          oc scale deployment ${DEPLOYMENT_NAME} -n openshift-pipelines --replicas=0

          echo "INFO: Hack job finished."
      restartPolicy: OnFailure
      serviceAccountName: openshift-gitops-argocd-application-controller-api
