apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-clusterrole-argocd-cmp-dns-reader.yaml
  - cluster-clusterrole-delete-project.yaml
  - cluster-clusterrole-edit-crd.yaml
  - cluster-crb-argocd-cmp-dns-reader.yaml
  - cluster-crb-delete-project-openshift-gitopsopenshift-gitops-argocd-application-controller.yaml
  - cluster-crb-edit-crd-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - cluster-crb-gitops-gitopsservice-edit.yaml
  - cluster-gitopsservice-cluster.yaml
  - cluster-group-cluster-admins.yaml
  - cluster-namespace-openshift-kube-controller-manager.yaml
  - openshift-gitops-argocd-openshift-gitops.yaml
  - cluster-cr-ack-config-operator.yaml
  - cluster-cr-cert-manager-operator.yaml
  - cluster-cr-cleanup-operator.yaml
  - cluster-cr-console-plugin-manager.yaml
  - cluster-cr-gpu-machineset-operator.yaml
  - cluster-crb-ack-config-operator.yaml
  - cluster-crb-cert-manager-operator.yaml
  - cluster-crb-cleanup-operator.yaml
  - cluster-crb-console-plugin-manager.yaml
  - cluster-crb-gpu-machineset-operator.yaml
  - openshift-gitops-configmap-cmp-plugin.yaml
  - openshift-gitops-job-cleanup-installer-pods.yaml
  - openshift-gitops-job-enable-gitops-console-plugin.yaml
  - ack-system-rb-ack-config-operator.yaml
  - ack-system-role-ack-config-operator.yaml
  - cert-manager-rb-cert-manager-operator.yaml
  - cert-manager-role-cert-manager-operator.yaml
  - kube-system-rb-ack-config-operator.yaml
  - kube-system-rb-cert-manager-operator.yaml
  - kube-system-role-ack-config-operator.yaml
  - kube-system-role-cert-manager-operator.yaml
  - monitoring-rb-grafana-datasource-configurator.yaml
  - monitoring-role-grafana-datasource-configurator.yaml
  - netobserv-rb-loki-s3-secret-creator.yaml
  - netobserv-role-loki-s3-secret-creator.yaml
  - openshift-config-rb-cert-manager-operator.yaml
  - openshift-config-role-cert-manager-operator.yaml
  - openshift-gitops-role-gpu-machineset-operator-openshift-gitops.yaml
  - openshift-gitops-role-odf-subscription-configurator-openshift-gitops.yaml
  - openshift-gitops-rolebinding-gpu-machineset-operator-openshift-gitops.yaml
  - openshift-gitops-rolebinding-odf-subscription-configurator-openshift-gitops.yaml
  - openshift-ingress-operator-rb-cert-manager-operator.yaml
  - openshift-ingress-operator-role-cert-manager-operator.yaml
  - openshift-ingress-rb-cert-manager-operator.yaml
  - openshift-ingress-role-cert-manager-operator.yaml
  - openshift-kube-controller-manager-rb-cleanup-operator.yaml
  - openshift-kube-controller-manager-role-cleanup-operator.yaml
  - openshift-logging-rb-loki-s3-secret-creator.yaml
  - openshift-logging-role-loki-s3-secret-creator.yaml
  - openshift-machine-api-rb-gpu-machineset-operator.yaml
  - openshift-machine-api-role-gpu-machineset-operator.yaml
  - openshift-operators-rb-dependency-waiter.yaml
  - openshift-operators-role-dependency-waiter.yaml
  - openshift-storage-rb-odf-subscription-configurator.yaml
  - openshift-storage-role-odf-subscription-configurator.yaml
  - openshift-gitops-serviceaccount-ack-config-operator.yaml
  - openshift-gitops-serviceaccount-cert-manager-operator.yaml
  - openshift-gitops-serviceaccount-cleanup-operator.yaml
  - openshift-gitops-serviceaccount-console-plugin-manager.yaml
  - openshift-gitops-serviceaccount-dependency-waiter.yaml
  - openshift-gitops-serviceaccount-grafana-datasource-configurator.yaml
  - openshift-gitops-serviceaccount-gpu-machineset-operator.yaml
  - openshift-gitops-serviceaccount-loki-s3-secret-creator.yaml
  - openshift-gitops-serviceaccount-odf-subscription-configurator.yaml
