apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cleanup-operator
  namespace: openshift-kube-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cleanup-operator
subjects:
- kind: ServiceAccount
  name: cleanup-operator
  namespace: openshift-gitops
