apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: grafana-datasource-configurator
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-datasource-configurator
subjects:
- kind: ServiceAccount
  name: grafana-datasource-configurator
  namespace: openshift-gitops
