apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: cleanup-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
- apiGroups:
  - operator.openshift.io
  resources:
  - openshiftbuilds
  verbs:
  - delete
