apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: update-odf-subscriptions-node-selector
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: update-odf-subscriptions-node-selector
    spec:
      containers:
        - name: patch-subscriptions
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e
              TARGET_NS="openshift-storage"
              echo "--- Starting ODF Subscription NodeSelector Patcher ---"
              echo "Target Namespace: $TARGET_NS"
              
              SUBSCRIPTIONS=(
                "cephcsi-operator-stable-4.20-redhat-operators-openshift-marketplace"
                "mcg-operator-stable-4.20-redhat-operators-openshift-marketplace"
                "ocs-client-operator-stable-4.20-redhat-operators-openshift-marketplace"
                "ocs-operator-stable-4.20-redhat-operators-openshift-marketplace"
                "odf-csi-addons-operator-stable-4.20-redhat-operators-openshift-marketplace"
                "odf-dependencies"
                "odf-prometheus-operator-stable-4.20-redhat-operators-openshift-marketplace"
                "recipe-stable-4.20-redhat-operators-openshift-marketplace"
                "rook-ceph-operator-stable-4.20-redhat-operators-openshift-marketplace"
              )

              PATCH='{"spec":{"config":{"nodeSelector":{"cluster.ocs.openshift.io/openshift-storage":""}}}}'

              for SUB in "${SUBSCRIPTIONS[@]}"; do
                echo "----------------------------------------------------------------"
                echo "Processing: $SUB"
                
                echo -n "Waiting for subscription..."
                while ! oc get subscription "$SUB" -n "$TARGET_NS" >/dev/null 2>&1; do
                  echo -n "."
                  sleep 5
                done
                echo " Found!"

                echo "Patching..."
                oc patch subscription "$SUB" -n "$TARGET_NS" --type=merge -p "$PATCH"
                echo "✅ Patched."
              done
              echo "----------------------------------------------------------------"
              echo "All done."
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      restartPolicy: OnFailure
      serviceAccountName: openshift-gitops-argocd-application-controller
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists