apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: enable-odf-console-plugins
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: enable-console-plugins
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          set -e
          echo "Checking if odf-console is already enabled..."
          if ! oc get console.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' | grep -qw "odf-console"; then
            echo "Enabling odf-console..."
            oc patch console.operator.openshift.io cluster --type=json -p='[{"op": "add", "path": "/spec/plugins/-", "value": "odf-console"}]'
            echo "Plugin odf-console added successfully."
          else
            echo "Plugin odf-console already exists. Nothing changed."
          fi

          echo "Checking if odf-client-console is already enabled..."
          if ! oc get console.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' | grep -qw "odf-client-console"; then
            echo "Enabling odf-client-console..."
            oc patch console.operator.openshift.io cluster --type=json -p='[{"op": "add", "path": "/spec/plugins/-", "value": "odf-client-console"}]'
            echo "Plugin odf-client-console added successfully."
          else
            echo "Plugin odf-client-console already exists. Nothing changed."
          fi
        image: registry.redhat.io/openshift4/ose-cli:latest
        name: enable-console-plugins
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
