apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: patch-console-odf-plugins
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: patch-console-odf-plugins
    spec:
      containers:
        - name: patch-console
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e
              echo "Ensuring ODF plugins are in Console plugins list..."

              if ! oc get console.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' | grep -qw "odf-console"; then
                echo "Adding odf-console to Console..."
                oc patch console.operator.openshift.io cluster --type=json -p='[{"op": "add", "path": "/spec/plugins/-", "value": "odf-console"}]'
                echo "✅ Plugin odf-console added."
              else
                echo "✅ Plugin odf-console already present."
              fi

              if ! oc get console.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' | grep -qw "odf-client-console"; then
                echo "Adding odf-client-console to Console..."
                oc patch console.operator.openshift.io cluster --type=json -p='[{"op": "add", "path": "/spec/plugins/-", "value": "odf-client-console"}]'
                echo "✅ Plugin odf-client-console added."
              else
                echo "✅ Plugin odf-client-console already present."
              fi
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists