apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-namespace-llmd-deploy-lab.yaml
- llmd-deploy-lab-cm-fast-track-code.yaml
- llmd-deploy-lab-job-fasttracker.yaml
- llmd-deploy-lab-job-mcg-bucket-models-rotation.yaml
- llmd-deploy-lab-llminferenceservice-granite-distributed.yaml
- llmd-deploy-lab-obc-models.yaml
- llmd-deploy-lab-rb-mcg-bucket-models-rotation.yaml
- llmd-deploy-lab-role-mcg-bucket-models-rotation.yaml
- llmd-deploy-lab-sa-kserve-s3-sa.yaml
- llmd-deploy-lab-sa-mcg-bucket-models-rotation.yaml
