apiVersion: v1
kind: Secret
metadata:
  name: aws-acme
  namespace: cert-manager
type: Opaque
stringData:
  awsAccessKey: CMP_PLACEHOLDER_AWS_ACCESS_KEY_ID
  awsSecretAccessKey: CMP_PLACEHOLDER_AWS_SECRET_ACCESS_KEY
