apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- cert-manager-clusterissuer-cluster.yaml
- cert-manager-configmap-scripts.yaml
- cert-manager-operator-operatorgroup-openshift-cert-manager-operator.yaml
- cert-manager-operator-subscription-openshift-cert-manager-operator.yaml
- cert-manager-secret-aws-acme.yaml
- cluster-certmanager-cluster.yaml
- cluster-crb-cert-manager-clusterissuer-edit.yaml
- cluster-namespace-cert-manager-operator.yaml
- openshift-gitops-job-create-cluster-cert-manager-resources.yaml
# DISABLED: Patch Jobs temporarily disabled
#- openshift-gitops-job-update-cluster-apiserver-cluster.yaml
#- openshift-gitops-job-update-openshift-ingress-operator-ingresscontroller-default.yaml
replacements:
- source:
    fieldPath: data.cert-manager
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: openshift-cert-manager-operator
