apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: update-cluster-apiserver-cluster
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: update-cluster-apiserver-cluster
    spec:
      containers:
        - name: update-cluster-apiserver-cluster
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e
              echo "Fetching cluster domain from DNS CR..."
              CLUSTER_DOMAIN=$(oc get dns.config.openshift.io/cluster -o jsonpath='{.spec.baseDomain}')
              echo "CLUSTER_DOMAIN=$CLUSTER_DOMAIN"

              echo "Building API URL..."
              API_URL="api.${CLUSTER_DOMAIN}"
              echo "API_URL=$API_URL"

              echo "Waiting for certificate to be created..."
              while ! oc get certificate api -n openshift-config 2>/dev/null 1>&2; do
                echo "Wait for certificate to be created."
                sleep 5
              done

              echo "Wait for certificate to be ready..."
              oc wait --for=condition=Ready --timeout=-1s certificate/api -n openshift-config

              echo "Update api config..."
              oc patch apiserver cluster --type merge -p '{"spec":{"servingCerts":{"namedCertificates":[{"names":["'$API_URL'"],"servingCertificate":{"name":"api-certificates"}}]}}}'

              echo "API server configuration updated successfully!" 
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists