apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: create-cluster-cert-manager-resources
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: create-cluster-cert-manager-resources
    spec:
      containers:
      - command:
        - /scripts/create-cert-manager-resources.sh
        image: registry.redhat.io/openshift4/ose-cli:latest
        name: create-cluster-cert-manager-resources
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 0755
          name: cert-manager-scripts
        name: scripts
