apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchdog-certmanager
  namespace: openshift-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchdog-certmanager
  template:
    metadata:
      labels:
        app: watchdog-certmanager
    spec:
      containers:
      - command:
        - /scripts/watchdog-certmanager.sh
        image: registry.redhat.io/openshift4/ose-cli:latest
        name: watchdog-certmanager
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - mountPath: /scripts
          name: scripts
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      restartPolicy: Always
      serviceAccountName: cert-manager-operator
      tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 0755
          name: cert-manager-scripts
        name: scripts
