apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: patch-ingresscontroller-default-certificate
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: patch-ingresscontroller-default-certificate
    spec:
      containers:
        - name: patch-ingresscontroller
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e
              echo "Waiting for ingress certificate to be created..."
              while ! oc get certificate ingress -n openshift-ingress 2>/dev/null 1>&2; do
                sleep 5
              done

              echo "Waiting for ingress certificate to be Ready..."
              oc wait --for=condition=Ready --timeout=-1s certificate/ingress -n openshift-ingress

              echo "Ensuring IngressController uses the cert-manager certificate..."
              oc patch ingresscontroller default -n openshift-ingress-operator --type merge \
                -p '{"spec":{"defaultCertificate":{"name":"ingress-certificates"}}}'
              echo "✅ IngressController default certificate configured."
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists