apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: api
  namespace: openshift-config
spec:
  commonName: CMP_PLACEHOLDER_OCP_API_DOMAIN
  dnsNames:
  - CMP_PLACEHOLDER_OCP_API_DOMAIN
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: cluster
  secretName: api-certificates
