apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: openshift-builds-operator
  namespace: openshift-builds
spec:
  channel: latest
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
  name: openshift-builds-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
