apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
    argocd.argoproj.io/sync-wave: '-1'
  name: check-and-wait-openshift-pipelines
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: check-and-wait-openshift-pipelines
    spec:
      containers:
        - name: check-and-wait-openshift-pipelines
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e
              echo "Check for an existing OpenShift Pipelines subscription..."
              if [[ $(oc get sub openshift-pipelines-operator-rh -n openshift-operators 2>/dev/null) ]]; then
                echo "Found OpenShift Pipeline Subscription in openshift-operators namespace."
                echo "Waiting the OpenShift GitOps Operator Subscription has the InstallPlan for the Operator..."
                oc wait sub openshift-pipelines-operator-rh -n openshift-operators --for jsonpath='{.status.installPlanRef.name}' --timeout -1s
                INSTALL_PLAN_NAME=$(oc get sub openshift-pipelines-operator-rh -n openshift-operators -o jsonpath='{.status.installPlanRef.name}')
                CSV_NAME=$(oc get ip $INSTALL_PLAN_NAME -n openshift-operators -o jsonpath='{.spec.clusterServiceVersionNames[0]}')
                echo "OpenShift Operator CSV has been instanciated: $CSV_NAME, we can now continue the OpenShift Build Operator installation"
              else
                echo "No OpenShift Pipeline subscription found, we will let OpenShift Build Operator to manage its own OpenShift Pipeline installation."
              fi
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
