apiVersion: v1
kind: Secret
metadata:
  name: ack-route53-user-secrets
  namespace: ack-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: CMP_AWS_ACCESS_KEY_ID_PLACEHOLDER
  AWS_SECRET_ACCESS_KEY: CMP_AWS_SECRET_ACCESS_KEY_PLACEHOLDER
