apiVersion: v1
kind: ConfigMap
metadata:
  name: ack-route53-user-config
  namespace: ack-system
data:
  ACK_ENABLE_DEVELOPMENT_LOGGING: "true"
  ACK_LOG_LEVEL: "info"
  ACK_RESOURCE_TAGS: "services.k8s.aws/controller-version=route53-1.2.0,services.k8s.aws/namespace=%K8S_NAMESPACE%"
  ACK_WATCH_NAMESPACE: ""
  AWS_ENDPOINT_URL: ""
  AWS_REGION: "CLUSTER_REGION"
  ENABLE_CARM: "false"
  ENABLE_LEADER_ELECTION: "true"
  FEATURE_GATES: ""
  LEADER_ELECTION_NAMESPACE: ""
  RECONCILE_DEFAULT_MAX_CONCURRENT_SYNCS: "1"
