apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- ack-system-configmap-ack-route53-user-config.yaml
- ack-system-operatorgroup-ack-route53-operator.yaml
- ack-system-secret-ack-route53-user-secrets.yaml
- ack-system-subscription-ack-route53-controller.yaml
- cluster-namespace-ack-system.yaml
replacements:
- source:
    fieldPath: data.ack-route53
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: ack-route53-controller
