apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-network-policies
rules:
- apiGroups:
  - policy.networking.k8s.io
  resources:
  - adminnetworkpolicies
  - baselineadminnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
