apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: cluster
spec:
  consolePlugin:
    advanced:
      scheduling:
        nodeSelector:
          node-role.kubernetes.io/infra: ''
        tolerations:
          - key: node-role.kubernetes.io/infra
            operator: Exists
  loki:
    enable: false

