apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamastack-postgresql
  namespace: external-db-llamastack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llamastack-postgresql
  template:
    metadata:
      labels:
        app: llamastack-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: llamastack-postgresql-credentials
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: llamastack-postgresql-credentials
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: llamastack-postgresql-credentials
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: registry.redhat.io/rhel9/postgresql-16:9.7
        name: postgresql
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -h 127.0.0.1 -U "$POSTGRESQL_USER" -d "$POSTGRESQL_DATABASE"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -h 127.0.0.1 -U "$POSTGRESQL_USER" -d "$POSTGRESQL_DATABASE"
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: llamastack-postgresql
