apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- ai-embedding-service-rb-allow-llamastack-access.yaml
- cluster-namespace-external-db-llamastack.yaml
- cluster-namespace-llamastack.yaml
- external-db-llamastack-deployment-llamastack-postgresql.yaml
- external-db-llamastack-pvc-llamastack-postgresql.yaml
- external-db-llamastack-secret-llamastack-postgresql-credentials.yaml
- external-db-llamastack-service-llamastack-postgresql.yaml
- llamastack-configmap-llama32-chat-template.yaml
- llamastack-inferenceservice-llamastack-model.yaml
- llamastack-llamastackdistribution-lsd-llama-pgvector-remote.yaml
- llamastack-sa-llamastack-model-sa.yaml
- llamastack-secret-llama-stack-secret.yaml
- llamastack-secret-pgvector-connection.yaml
- llamastack-servingruntime-llamastack-model.yaml
- redhat-ods-applications-cm-llamastack-embedding-provider.yaml
- redhat-ods-applications-llamastackdistribution-llamastack-pgvector.yaml
- redhat-ods-applications-rb-llamastack-use-scc.yaml
- redhat-ods-applications-secret-llamastack-db-credentials.yaml
