apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: llamastack
  namespace: llamastack
spec:
  replicas: 1
  server:
    containerSpec:
      env:
      - name: EMBEDDING_MODEL
        value: granite-embedding
      - name: EMBEDDING_PROVIDER_MODEL_ID
        value: granite-embedding
      - name: ENABLE_PGVECTOR
        value: "true"
      - name: INFERENCE_MODEL
        value: granite-llm
      - name: PGVECTOR_DB
        valueFrom:
          secretKeyRef:
            key: PGVECTOR_DB
            name: pgvector-connection
      - name: PGVECTOR_HOST
        valueFrom:
          secretKeyRef:
            key: PGVECTOR_HOST
            name: pgvector-connection
      - name: PGVECTOR_PASSWORD
        valueFrom:
          secretKeyRef:
            key: PGVECTOR_PASSWORD
            name: pgvector-connection
      - name: PGVECTOR_PORT
        valueFrom:
          secretKeyRef:
            key: PGVECTOR_PORT
            name: pgvector-connection
      - name: PGVECTOR_USER
        valueFrom:
          secretKeyRef:
            key: PGVECTOR_USER
            name: pgvector-connection
      - name: POSTGRES_DB
        value: llamastackdb
      - name: POSTGRES_HOST
        value: llamastack-postgresql.external-db-llamastack.svc.cluster.local
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: POSTGRES_PASSWORD
            name: postgres-secret
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_USER
        value: llamastack
      - name: VLLM_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: token
            name: granite-llm-sa-token
      - name: VLLM_EMBEDDING_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: token
            name: granite-embedding-sa-token
      - name: VLLM_EMBEDDING_MAX_TOKENS
        value: "512"
      - name: VLLM_EMBEDDING_TLS_VERIFY
        value: "false"
      - name: VLLM_EMBEDDING_URL
        value: https://granite-embedding-predictor.llamastack.svc.cluster.local:8443/v1
      - name: VLLM_TLS_VERIFY
        value: "false"
      - name: VLLM_URL
        value: https://granite-llm-predictor.llamastack.svc.cluster.local:8443/v1
      port: 8321
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi
    distribution:
      name: rh-dev
    storage:
      size: 20Gi
  network:
    allowedFrom:
      namespaces:
      - ai-generation-llm-rag
