apiVersion: v1
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type-protocol: oci
    opendatahub.io/connection-type-ref: oci-v1
    openshift.io/display-name: Quay Red Hat AI Services
  labels:
    opendatahub.io/dashboard: "true"
  name: quay-redhat-ai-services
  namespace: llamastack
type: Opaque
data:
  OCI_HOST: cXVheS5pbw==
