apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-ingestion-storage
  namespace: llamastack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
