kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-clustermanagementaddon
rules:
  - verbs:
      - '*'
    apiGroups:
      - addon.open-cluster-management.io
    resources:
      - clustermanagementaddons
