apiVersion: addon.open-cluster-management.io/v1beta1
kind: ClusterManagementAddOn
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: work-manager
spec:
  defaultConfigs:
    - group: addon.open-cluster-management.io
      name: deploy-config
      namespace: open-cluster-management-hub
      resource: addondeploymentconfigs
