apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: search-edit
  namespace: open-cluster-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: search-edit
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
