apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- cluster-clusterrole-manage-openshiftbuilds.yaml
- cluster-crb-manage-openshiftbuilds-gitops.yaml
- cluster-namespace-openshift-builds.yaml
- cluster-openshiftbuild-cluster.yaml
- openshift-builds-operatorgroup-openshift-builds-operator.yaml
- openshift-builds-subscription-openshift-builds-operator.yaml
- openshift-gitops-job-delete-openshift-builds-resources.yaml
replacements:
- source:
    fieldPath: data.openshift-builds
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: openshift-builds-operator
