apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-namespace-model-deploy-lab.yaml
- model-deploy-lab-cm-ingestion-code.yaml
- model-deploy-lab-inferenceservice-granite-3-3-2b-instruct.yaml
- model-deploy-lab-job-mcg-bucket-models-rotation.yaml
- model-deploy-lab-job-model-ingest.yaml
- model-deploy-lab-obc-models.yaml
- model-deploy-lab-rb-mcg-bucket-models-rotation.yaml
- model-deploy-lab-role-mcg-bucket-models-rotation.yaml
- model-deploy-lab-sa-mcg-bucket-models-rotation.yaml
- model-deploy-lab-sa-model-ingestion.yaml
- model-deploy-lab-servingruntime-vllm-cuda-runtime.yaml
- rhoai-model-registries-rb-model-ingest-job-model-deploy-lab.yaml
- rhoai-model-registries-role-model-ingest-job-model-deploy-lab.yaml
