apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-ingest-job-model-deploy-lab
  namespace: rhoai-model-registries
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: model-ingest-job-model-deploy-lab
subjects:
- kind: ServiceAccount
  name: model-ingestion
  namespace: model-deploy-lab
