apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: model-ingest-job-ai-project-b
  namespace: rhoai-model-registries
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: model-ingest-job-ai-project-b
subjects:
- kind: ServiceAccount
  name: model-ingestion
  namespace: ai-project-b
