apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- cluster-namespace-rhacs-operator.yaml
- cluster-namespace-stackrox.yaml
- rhacs-operator-operatorgroup-rhacs-operator.yaml
- rhacs-operator-subscription-rhacs-operator.yaml
- stackrox-securedcluster-stackrox-secured-cluster-services.yaml
replacements:
- source:
    fieldPath: data.rhacs
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: rhacs-operator
