apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-golden-dataset-pv-retain
  namespace: ai-supply-chain
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
