apiVersion: v1
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type: "uri"
    opendatahub.io/connection-type-protocol: "uri" # required for RHOAI 3.3 backend routing
    openshift.io/description: "Direct link to a specific external model file."
    openshift.io/display-name: "Custom URI Link"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true" # required for RHOAI 3.3 dashboard visibility
  name: custom-uri-link
  namespace: ai-supply-chain
stringData:
  URI: "https://huggingface.co/redhat/granite-7b-instruct/resolve/main/model.safetensors"
type: Opaque
