apiVersion: v1
kind: Secret
metadata:
  annotations:
    opendatahub.io/connection-type: "oci"
    opendatahub.io/connection-type-protocol: "oci" # required for RHOAI 3.3 backend routing
    openshift.io/description: "Public OCI image from Red Hat Modelcar catalog."
    openshift.io/display-name: "Granite 3.2 8B (Modelcar)"
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true" # required for RHOAI 3.3 dashboard visibility
  name: granite-3-8b-modelcar
  namespace: ai-supply-chain
stringData:
  URI: "oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.2-8b-instruct"
type: Opaque
