apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    created-by: "platform-automation"
    opendatahub.io/dashboard: "true"
    opendatahub.io/storage-type: "general-purpose"
  name: golden-dataset
  namespace: ai-supply-chain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
