apiVersion: v1
kind: Pod
metadata:
  name: storage-binder
  namespace: ai-supply-chain
spec:
  containers:
    - command: ["tail", "-f", "/dev/null"]
      image: registry.access.redhat.com/ubi9/ubi-minimal
      name: binder
      resources:
        requests:
          cpu: "10m"
          memory: "50Mi"
      volumeMounts:
        - mountPath: "/data"
          name: my-vol
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: golden-dataset
