apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster-versions
  namespace: openshift-gitops
data:
  # Observability
  cluster-logging: "stable-6.4"
  cluster-observability: "stable"
  grafana: "v5"
  loki: "stable-6.4"
  network-observability: "stable"
  opentelemetry: "stable"
  tempo: "stable"

  # Integration
  openshift-service-mesh: "stable"
  rhbk-operator: "stable-v26.4"  # Red Hat build of Keycloak

  # API Gateway (Red Hat Connectivity Link - Kuadrant)
  authorino-operator: "stable"
  dns-operator: "stable"
  limitador-operator: "stable"
  rhcl-operator: "stable"

  # CI/CD & Dev Tools
  cert-manager: "stable-v1.18"
  devworkspace: "fast"  # Usually coupled with Web Terminal
  openshift-builds: "builds-1.6"
  openshift-gitops: "gitops-1.19"
  openshift-pipelines: "pipelines-1.20"
  web-terminal: "fast"

  # Infrastructure & Storage
  ack-route53: "alpha"
  nfd: "stable"  # Node Feature Discovery
  nfs-provisioner: "alpha"
  
  # OpenShift Data Foundation (ODF)
  # All ODF components typically share the same version lifecycle
  odf: "stable-4.20"

  # AI
  kueue: "stable-v1.2"
  nvidia-gpu-operator: "v25.10"
  rhoai: "stable-3.3"

  # Cluster management
  rhacm: "release-2.15"
  rhacs: "rhacs-4.9"