apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-operator-namespace.yaml
  - grafana-operator-operatorgroup-grafana-operator.yaml
  - grafana-operator-subscription-grafana-operator.yaml
