apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ossmconsole
  namespace: openshift-operators
spec:
  channel: candidate
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
  installPlanApproval: Automatic
  name: ossmconsole
  source: community-operators
  sourceNamespace: openshift-marketplace

