apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: gpu-cluster-policy
spec:
  daemonsets: {}
  dcgm: {}
  dcgmExporter: {}
  devicePlugin: {}
  driver:
    enabled: true
  gfd: {}
  nodeStatusExporter:
    enabled: true
  operator:
    defaultRuntime: crio
  toolkit: {}
