apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: pipeline-artifacts
  namespace: ai-generation-llm-rag
spec:
  generateBucketName: pipeline-artifacts
  storageClassName: openshift-storage.noobaa.io
