apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines
  namespace: ai-generation-llm-rag
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  apiServer:
    stripEOF: true
    terminateStatus: Cancelled
    autoUpdatePipelineDefaultVersion: true
    archiveLogs: false
    collectMetrics: true
  database:
    externalDB:
      host: dspa-mariadb.external-rhoai-db.svc.cluster.local
      port: "3306"
      username: mlpipeline
      pipelineDBName: mlpipeline
      passwordSecret:
        name: dspa-mariadb-password
        key: password
  objectStorage:
    externalStorage:
      host: BUCKET_HOST_PLACEHOLDER
      port: "443"
      bucket: BUCKET_NAME_PLACEHOLDER
      scheme: https
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: pipeline-artifacts
  persistenceAgent:
    deploy: true
  scheduledWorkflow:
    deploy: true
