kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-kubeflow-edit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups:
  - pipelines.kubeflow.org
  resources:
  - pipelines
  - pipelineversions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
