apiVersion: v1
kind: Secret
metadata:
  annotations:
    security.internal/credential-type: demo-placeholder
  name: mysql-credentials
  namespace: external-db-model-registry
stringData:
  MYSQL_DATABASE: modelregistrydb
  MYSQL_PASSWORD: changeme-demo-only
  MYSQL_USER: modelregistry
