apiVersion: v1
kind: Secret
metadata:
  annotations:
    security.internal/credential-type: demo-placeholder
  name: maas-postgresql-credentials
  namespace: external-db-maas
stringData:
  POSTGRESQL_USER: maas
  POSTGRESQL_PASSWORD: changeme-demo-only
  POSTGRESQL_DATABASE: maasdb
