apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genai-playground-postgresql
  namespace: external-db-genai-playground
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
