apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogxserver-postgresql
  namespace: external-db-ogxserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
