apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ogxserver-metadata-postgresql
  namespace: external-db-ogxserver-metadata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
