apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamastack-postgresql
  namespace: external-rhoai-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llamastack-postgresql
  template:
    metadata:
      labels:
        app: llamastack-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: llamastack-postgresql-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: llamastack-postgresql-credentials
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: llamastack-postgresql-credentials
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:15
        name: postgresql
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: llamastack-postgresql
