apiVersion: v1
kind: ConfigMap
metadata:
  name: ogxserver-vector-postgresql-init
  namespace: external-db-ogxserver-vector
data:
  enable-pgvector.sh: |
    #!/bin/bash
    psql -U postgres -d "${POSTGRESQL_DATABASE}" -c "CREATE EXTENSION IF NOT EXISTS vector;"
