apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dspa-mariadb
  namespace: external-rhoai-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
