apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: external-db-maas
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: maas-postgresql
