apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- ai-generation-llm-rag-cm-pipeline-docling-standard.yaml
- ai-generation-llm-rag-dspa-pipelines.yaml
- ai-generation-llm-rag-obc-pipeline-artifacts.yaml
- ai-generation-llm-rag-rb-pipeline-configmap-reader.yaml
- ai-generation-llm-rag-role-pipeline-configmap-reader.yaml
- ai-generation-llm-rag-secret-dspa-mariadb-password.yaml
- openshift-gitops-cm-pipeline-upload-script.yaml
- openshift-gitops-job-upload-pipeline-docling-standard.yaml
- openshift-gitops-sa-pipeline-uploader.yaml
- cluster-cr-edit-rhoai-dashboard-config.yaml
- cluster-crb-datascienceclusters-edit-gitops.yaml
- cluster-datasciencecluster-default-dsc.yaml
- cluster-namespace-ai-generation-llm-rag.yaml
- cluster-namespace-external-rhoai-db.yaml
- cluster-namespace-llamastack.yaml
- cluster-namespace-redhat-ods-applications.yaml
- cluster-namespace-redhat-ods-operator.yaml
- external-rhoai-db-configmap-dspa-mariadb-tls-config.yaml
- external-rhoai-db-deployment-dspa-mariadb.yaml
- external-rhoai-db-deployment-llamastack-postgresql.yaml
- external-rhoai-db-pvc-dspa-mariadb.yaml
- external-rhoai-db-pvc-llamastack-postgresql.yaml
- external-rhoai-db-secret-dspa-mariadb-credentials.yaml
- external-rhoai-db-secret-llamastack-postgresql-credentials.yaml
- external-rhoai-db-service-dspa-mariadb.yaml
- external-rhoai-db-service-llamastack-postgresql.yaml
- llamastack-configmap-llama32-chat-template.yaml
- llamastack-inferenceservice-granite-embedding.yaml
- llamastack-inferenceservice-llamastack-model.yaml
- llamastack-llamastackdistribution-lsd-llama-pgvector-remote.yaml
- llamastack-sa-granite-embedding-sa.yaml
- llamastack-sa-llamastack-model-sa.yaml
- llamastack-secret-granite-embedding-sa-token.yaml
- llamastack-secret-llama-stack-secret.yaml
- llamastack-secret-pgvector-connection.yaml
- llamastack-servingruntime-granite-embedding.yaml
- llamastack-servingruntime-llamastack-model.yaml
- openshift-ingress-gateway-maas-default-gateway.yaml
- redhat-ods-applications-cm-llamastack-embedding-provider.yaml
- redhat-ods-applications-hardwareprofile-gpus.yaml
- redhat-ods-applications-odhdashboardconfig-odh-dashboard-config.yaml
- redhat-ods-applications-rb-llamastack-use-scc.yaml
- redhat-ods-applications-secret-llamastack-db-credentials.yaml
- redhat-ods-operator-operatorgroup-rhods-operator.yaml
- redhat-ods-operator-subscription-rhods-operator.yaml
replacements:
- source:
    fieldPath: data.rhoai
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: rhods-operator
