apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- cluster-cr-edit-rhoai-dashboard-config.yaml
- cluster-crb-datascienceclusters-edit-gitops.yaml
- cluster-datasciencecluster-default-dsc.yaml
- cluster-namespace-external-llamastack-db.yaml
- cluster-namespace-llamastack.yaml
- cluster-namespace-redhat-ods-applications.yaml
- cluster-namespace-redhat-ods-operator.yaml
- external-llamastack-db-deployment-postgresql.yaml
- external-llamastack-db-pvc-postgresql-data.yaml
- external-llamastack-db-secret-postgresql-credentials.yaml
- external-llamastack-db-service-postgresql.yaml
- llamastack-configmap-llama32-chat-template.yaml
- llamastack-inferenceservice-granite-embedding.yaml
- llamastack-secret-pgvector-connection.yaml
- llamastack-servingruntime-granite-embedding.yaml
- openshift-ingress-gateway-maas-default-gateway.yaml
- redhat-ods-applications-cm-llamastack-embedding-provider.yaml
- redhat-ods-applications-hardwareprofile-gpus.yaml
# DISABLED FOR TESTING: LlamaStackDistribution CR
# - redhat-ods-applications-llamastackdistribution-llamastack-pgvector.yaml
- redhat-ods-applications-odhdashboardconfig-odh-dashboard-config.yaml
- redhat-ods-applications-rb-llamastack-use-scc.yaml
- redhat-ods-applications-secret-llamastack-db-credentials.yaml
- redhat-ods-operator-operatorgroup-rhods-operator.yaml
- redhat-ods-operator-subscription-rhods-operator.yaml
replacements:
- source:
    fieldPath: data.rhoai
    kind: ConfigMap
    name: cluster-versions
  targets:
  - fieldPaths:
    - spec.channel
    select:
      kind: Subscription
      name: rhods-operator
