apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vllm-llama32-3b
  name: vllm-llama32-3b
  namespace: llamastack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-llama32-3b
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vllm-llama32-3b
    spec:
      containers:
      - args:
        - serve
        - ibm-granite/granite-3.3-2b-instruct
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        - --device
        - cpu
        - --max-model-len
        - "2048"
        - --disable-async-output-proc
        - --worker-cls
        - vllm.worker.cpu_worker.CPUWorker
        command:
        - vllm
        env:
        - name: HF_HUB_OFFLINE
          value: "0"
        - name: VLLM_CPU_ONLY
          value: "1"
        - name: VLLM_WORKER_MULTIPROC_METHOD
          value: spawn
        - name: VLLM_USE_MODELSCOPE
          value: "false"
        image: quay.io/opendatahub/vllm:stable
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 5
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 10
        name: vllm
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 5
          initialDelaySeconds: 600
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "4"
            memory: 12Gi
          requests:
            cpu: "2"
            memory: 8Gi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/worker
        operator: Exists
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 8Gi
        name: dshm
