apiVersion: datasciencepipelinesapplications.opendatahub.io/v1alpha1
kind: DataScienceProject
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    opendatahub.io/dashboard: "true"
  labels:
    opendatahub.io/dashboard: "true"
  name: llamastack
  namespace: llamastack
spec:
  displayName: Llama Stack
  description: Llama Stack deployment with vLLM inference and pgvector storage
