apiVersion: v1
kind: Service
metadata:
  labels:
    app: vllm-llama32-3b
  name: vllm-llama32-3b
  namespace: llamastack
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: vllm-llama32-3b
  type: ClusterIP
