apiVersion: v1
kind: Service
metadata:
  labels:
    app: vllm-granite-embedding
  name: vllm-granite-embedding
  namespace: llamastack
spec:
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: vllm-granite-embedding
  type: ClusterIP
