apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maas-db-secret
  namespace: redhat-ods-applications
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - patch
  - update
