apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: llamastack-pgvector
  namespace: redhat-ods-applications
spec:
  replicas: 1
  server:
    containerSpec:
      env:
      - name: EMBEDDING_MODEL
        value: granite-embedding-125m-english
      - name: EMBEDDING_URL
        value: http://vllm-granite-embedding.llamastack.svc.cluster.local:8001/v1
      - name: INFERENCE_MODEL
        value: granite-3.3-2b-instruct
      - name: POSTGRES_HOST
        value: postgresql.external-llamastack-db.svc.cluster.local
      - name: VLLM_TLS_VERIFY
        value: "false"
      - name: VLLM_URL
        value: http://vllm-llama32-3b.llamastack.svc.cluster.local:8000/v1
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            key: POSTGRES_DB
            name: llamastack-db-credentials
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            key: POSTGRES_USER
            name: llamastack-db-credentials
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: POSTGRES_PASSWORD
            name: llamastack-db-credentials
      port: 8321
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 2Gi
    distribution:
      name: rh-dev
