apiVersion: config.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  networkDiagnostics:
    sourcePlacement:
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/infra: ''
      tolerations:
        - operator: Exists