apiVersion: batch/v1
kind: Job
metadata:
  name: lab-job-3-high
  namespace: ai-team-a
  labels:
    kueue.x-k8s.io/priority-class: high-priority
    kueue.x-k8s.io/queue-name: team-a-queue
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: dummy
        image: bash:5
        command: ["sleep", "60"]
        resources:
          requests:
            cpu: 4
      restartPolicy: Never
