apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-acm-managed
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - branch: master
        item: rhacm
  template:
    metadata:
      name: '{{item}}'
    spec:
      project: default
      source: !!python/object/apply:collections.OrderedDict
      - - - path
          - components/{{item}}/overlays/managed
        - - repoURL
          - https://github.com/lautou/ocp-open-env-install-tool.git
        - - targetRevision
          - '{{branch}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
      ignoreDifferences:
      - !!python/object/apply:collections.OrderedDict
        - - - group
            - ''
          - - jsonPointers
            - - /metadata/labels
              - /metadata/annotations
              - /metadata/ownerReferences
          - - kind
            - ConfigMap
          - - name
            - cluster-versions
      - !!python/object/apply:collections.OrderedDict
        - - - group
            - ''
          - - jqPathExpressions
            - - .imagePullSecrets[] | select(.name | startswith("klusterlet-dockercfg-"))
          - - kind
            - ServiceAccount
          - - name
            - klusterlet
