apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - TEMPORARY-FIX-openshift-apiserver-networkpolicy-allow-check-endpoints-monitoring.yaml
  - cluster-apiserver-cluster.yaml
  - cluster-namespace-openshift-config.yaml
  - openshift-apiserver-rb-networkpolicy-manager.yaml
  - openshift-apiserver-role-networkpolicy-manager.yaml
