apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: networkpolicy-manager
  namespace: openshift-apiserver
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
