apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-dev-terminal
resources:
  - ../../base
  - cluster-namespace-openshift-dev-terminal-operators.yaml
  - openshift-dev-terminal-operators-operatorgroup-openshift-dev-terminal-operators.yaml
