apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit-oauth
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - oauths
  verbs:
  - get
  - list
  - update
  - watch
