apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- apicurio-registry-operatorgroup-apicurio-registry.yaml
- cluster-namespace-apicurio-registry.yaml
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: apicurio-registry
  target:
    kind: Subscription
    name: apicurio-registry
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: apicurio-registry
  target:
    kind: ConfigMap
    name: cluster-versions
