apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
spec:
  generators:
  - list:
      elements:
      - item: test
  template:
    metadata:
      name: '{{item}}'
    spec:
      project: default
      source:
        repoURL: https://gitlab.consulting.redhat.com/openshift-toolkit/ocp-open-env-install-tool.git
        path: argocd/{{item}}/overlays/default
        targetRevision: modularization
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
