apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  name: cluster
spec:
  plugins:
    - acm
    - gitops-plugin
    - logging-view-plugin
    - mce
    - monitoring-plugin
    - netobserv-plugin
    - odf-client-console
    - odf-console
    - pipelines-console-plugin
