apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    openshift.io/node-selector: "cluster.ocs.openshift.io/openshift-storage="
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "key":
      "node.ocs.openshift.io/storage"}]
  name: openshift-storage
  labels:
    openshift.io/cluster-monitoring: "true"
