apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-ingress-certificate-ingress
  namespace: openshift-gitops
data:
  openshift-ingress-certificate-ingress.yaml: |-
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: ingress 
      namespace: openshift-ingress
    spec:
      isCA: false
      commonName: "apps.CLUSTER_BASE_DOMAIN" 
      secretName: ingress-certificates 
      dnsNames:
      - "apps.CLUSTER_BASE_DOMAIN" 
      - "*.apps.CLUSTER_BASE_DOMAIN" 
    issuerRef:
      name: cluster 
      kind: ClusterIssuer
