apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-api-default
  namespace: openshift-gitops
data:
  cluster-apiserver-cluster.yaml: |-
    apiVersion: config.openshift.io/v1
    kind: APIServer
    metadata:
      name: cluster
    spec:
      servingCerts:
        namedCertificates:
        - names:
          - FQDN
          servingCertificate:
            name: api-certificates
