apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
    argocd.argoproj.io/sync-wave: '1'
  name: create-cert-manager-secret-aws-acme
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: create-cert-manager-secret-aws-acme
    spec:
      initContainers:
        - name: create-cert-manager-secret-aws-acme-and-extract-install-config
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              echo "Read the secret for AWS cloud provider"
              while ! oc get secret aws-creds -n kube-system 2>/dev/null 1>&2; do echo "Waiting for secret aws-creds in namespace kube-system."; done
              ACCESS_KEY=$(oc get secret aws-creds -n kube-system --template={{.data.aws_access_key_id}} | base64 -d)
              SECRET_KEY=$(oc get secret aws-creds -n kube-system --template={{.data.aws_secret_access_key}} | base64 -d)
              echo "Create the aws-acme secret"
              oc delete secret generic aws-acme -n cert-manager --ignore-not-found
              oc create secret generic aws-acme -n cert-manager --from-literal awsAccessKey=$ACCESS_KEY --from-literal awsSecretAccessKey=$SECRET_KEY
              oc extract cm/cluster-config-v1 --keys install-config --to /data -n kube-system
              oc extract cm/clusterissuer-cluster --keys cluster-clusterissuer-cluster.yaml --to /data -n openshift-gitops
          volumeMounts:
          - name: shared-data
            mountPath: /data
      containers:
        - name: extract-region
          image: quay.io/multi-arch/yq:4.35.2
          command:
          - /bin/sh
          args:
          - '-c'
          - |
            REGION=$(yq e '.platform.aws.region' /data/install-config)
            echo REGION=$REGION
            yq e ".spec.acme.solvers[0].dns01.route53.region = '$REGION'" -i /data/cluster-clusterissuer-cluster.yaml
            cat /data/cluster-clusterissuer-cluster.yaml
          volumeMounts:
          - name: shared-data
            mountPath: /data
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      volumes:
      - name: shared-data
        empty-dir: {}
