apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: instance
  namespace: openshift-logging
spec:
  collector:
    tolerations:
    - key: node-role.kubernetes.io/infra
      operator: Exists
  outputs:
  - name: default-lokistack
    type: lokiStack
    lokiStack:
      target:
        name: logging-loki
        namespace: openshift-logging
      authentication:
        token:
          from: serviceAccount
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  - inputRefs:
    - application
    - infrastructure
    name: default-logstore
    outputRefs:
    - default-lokistack
  serviceAccount:
    name: collector
