apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
    argocd.argoproj.io/sync-wave: '1'
  name: update-openshift-ingress-operator-ingresscontroller-default
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: update-openshift-ingress-operator-ingresscontroller-default
    spec:
      containers:
        - name: update-openshift-ingress-operator-ingresscontroller-default
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              while ! oc get certificate ingress -n openshift-ingress 2>/dev/null 1>&2; do echo "Wait for certificate to be created."; done
              echo "Wait for certificate to be ready"
              oc wait --for=condition=Ready certificate/ingress -n openshift-ingress
              echo "Update ingress controller config"
              oc extract cm/openshift-ingress-operator-ingresscontroller-default --keys openshift-ingress-operator-ingresscontroller-default.yaml --to /data -n openshift-gitops
              cat /data/openshift-ingress-operator-ingresscontroller-default.yaml
              echo
              oc apply -f /data/openshift-ingress-operator-ingresscontroller-default.yaml
          volumeMounts:
          - name: shared-data
            mountPath: /data
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      volumes:
      - name: shared-data
        empty-dir: {}
