apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterissuer-cluster
  namespace: openshift-gitops
data:
  cluster-clusterissuer-cluster.yaml: |-
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: cluster
    spec:
      acme:
        privateKeySecretRef:
          name: acme-global
        server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
        solvers:
          - dns01:
              route53:
                accessKeyIDSecretRef:
                  key: awsAccessKey
                  name: aws-acme
                region: REPLACEME
                secretAccessKeySecretRef:
                  key: awsSecretAccessKey
                  name: aws-acme
