apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-builds-operator
  namespace: openshift-operators
spec:
  channel: latest
  name: openshift-builds-operator 
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
