apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
    argocd.argoproj.io/sync-wave: '1'
  name: create-machineautoscaler
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: create-machineautoscaler
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      restartPolicy: Never
      containers:
        - name: create-machineautoscaler
          image: quay.io/devfile/universal-developer-image:ubi9-latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e

              # 1. Wait for ConfigMap
              echo "Waiting for ConfigMap 'machineautoscaler'..."
              until oc get cm machineautoscaler -n openshift-gitops &> /dev/null; do
                sleep 5
              done
              MAS_TEMPLATE=$(oc extract cm/machineautoscaler -n openshift-gitops --keys machineautoscaler.yaml --to -)

              # 2. Get ALL MachineSets names first
              echo "Listing all MachineSets..."
              ALL_MS=$(oc get machinesets -n openshift-machine-api -o jsonpath='{.items[*].metadata.name}')

              # 3. Process each MachineSet individually
              for MS_NAME in $ALL_MS; do
                echo "------------------------------------------------"
                echo "Inspecting MachineSet: $MS_NAME"

                # WAITING LOOP: Wait for the annotation to be generated by the controller
                # We treat "null" as "not ready yet"
                while true; do
                  # Use jq to safely extract the annotation, returns empty string if null
                  GPU_VAL=$(oc get machineset $MS_NAME -n openshift-machine-api -o json | jq -r '.metadata.annotations["machine.openshift.io/GPU"] // ""')

                  if [[ -n "$GPU_VAL" ]]; then
                    echo "Annotation found. GPU Value: $GPU_VAL"
                    break
                  fi
                  
                  echo "Waiting for 'machine.openshift.io/GPU' annotation on $MS_NAME..."
                  sleep 5
                done

                # DECISION LOGIC
                if [[ "$GPU_VAL" != "0" ]]; then
                  echo ">> GPU detected ($GPU_VAL). Creating MachineAutoscaler..."
                  
                  # Idempotent apply
                  echo "$MAS_TEMPLATE" | \
                    sed "s/name: machineset/name: $MS_NAME/g" | \
                    oc apply -n openshift-machine-api -f -
                else
                  echo ">> No GPU (Value is 0). Skipping."
                fi
              done

              echo "------------------------------------------------"
              echo "All MachineSets processed."