apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-pipelines-operator
resources:
  - cluster-namespace-openshift-pipelines-operator.yaml
  - openshift-pipelines-operator-operatorgroup-openshift-pipelines-operator.yaml
  - openshift-gitops-namespace-job-enable-pipelines-console-plugin.yaml
  - ../../common
  - ../../base/cluster-crb-tektonconfigs.operator.tekton.dev-v1alpha1-edit-openshift-gitops-openshift-gitops-argocd-application-controller.yaml
  - ../../base/cluster-tektonconfig-config.yaml
  - ../../base/openshift-operators-subscription-openshift-pipelines-operator.yaml
replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.openshift-pipelines
    targets:
      - select:
          kind: Subscription
          name: openshift-pipelines-operator
        fieldPaths:
          - spec.channel
