apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-pipelines-operator
resources:
  - ../../base
  - cluster-namespace-openshift-pipelines-operator.yaml
  - openshift-pipelines-operator-operatorgroup-openshift-pipelines-operator.yaml
