apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-crb-registry-operator-admin.yaml
  - cluster-imagepruner-cluster.yaml
  - cluster-imageregistry-config-cluster.yaml
