apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-logging-small
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - branch: master
        item: openshift-logging
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io/background
      name: '{{item}}'
    spec:
      project: default
      source:
        path: components/{{item}}/overlays/1x.small
        plugin:
          name: cluster-domain-replacer
        repoURL: https://github.com/lautou/ocp-open-env-install-tool.git
        targetRevision: '{{branch}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
      ignoreDifferences:
      - group: 
        jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /metadata/ownerReferences
        kind: ConfigMap
        name: cluster-versions
