apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: stable
  config:
    nodeSelector:
      node-role.kubernetes.io/infra= ''
    tolerations:
      - key: node.ocs.openshift.io/storage
        operator: Equal
        value: "true"
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace