apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: logging
spec:
  deployment:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - operator: Exists
        key: node-role.kubernetes.io/infra
  logging:
    lokiStack:
      name: logging-loki
    logsLimit: 50
    timeout: 30s
  type: Logging