apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: odf
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: Exists
  storageClassName: local-volume-odf
  tolerations:
    - key: node.ocs.openshift.io/storage
      operator: Exists
  volumeMode: Block