apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-ai
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - branch: master
        item: kueue
      - branch: master
        item: leader-work-set
      - branch: master
        item: nvidia-gpu-operator
      - branch: master
        item: rh-connectivity-link
      - branch: master
        item: rhoai
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io/background
      name: '{{item}}'
    spec:
      project: default
      source:
        path: components/{{item}}/overlays/default
        repoURL: https://github.com/lautou/ocp-open-env-install-tool.git
        targetRevision: '{{branch}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
      ignoreDifferences:
      - group: 
        jsonPointers:
        - /metadata/labels
        - /metadata/annotations
        - /metadata/ownerReferences
        kind: ConfigMap
        name: cluster-versions
      - group: opendatahub.io
        jsonPointers:
        - /metadata/annotations
        - /metadata/labels
        - /metadata/ownerReferences
        - /spec/hardwareProfileOrder
        - /spec/templateDisablement
        - /spec/templateOrder
        kind: OdhDashboardConfig
        name: odh-dashboard-config
      - group: infrastructure.opendatahub.io
        jsonPointers:
        - /metadata/annotations/opendatahub.io~1dashboard-feature-visibility
        - /metadata/annotations/opendatahub.io~1disabled
        - /metadata/annotations/opendatahub.io~1modified-date
        kind: HardwareProfile
