apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - cluster-namespace-kuadrant-system.yaml
  - kuadrant-system-operatorgroup-rhcl.yaml
  - kuadrant-system-subscription-rhcl-operator.yaml
  - kuadrant-system-kuadrant-kuadrant.yaml
  - openshift-gitops-job-enable-kuadrant-console-plugin.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.rhcl-operator
    targets:
      - select:
          kind: Subscription
          name: rhcl-operator
        fieldPaths:
          - spec.channel
