apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - openshift-operators-subscription-rhcl-operator.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-versions
      fieldPath: data.rhcl-operator
    targets:
      - select:
          kind: Subscription
          name: rhcl-operator
        fieldPaths:
          - spec.channel
