apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: thanos-query-ds
  namespace: monitoring
spec:
  datasource:
    access: proxy
    isDefault: true
    jsonData:
      httpHeaderName1: Authorization
      tlsAuthWithCACert: true
    name: "Prometheus - Thanos"
    secureJsonData:
      httpHeaderValue1: "Bearer ${token}"
      tlsCACert: "${service-ca.crt}"
    type: prometheus
    url: https://thanos-querier.openshift-monitoring.svc:9091
  instanceSelector:
    matchLabels:
      dashboards: grafana
  valuesFrom:
  - targetPath: "secureJsonData.httpHeaderValue1"
    valueFrom:
      secretKeyRef:
        name: grafana-datasource-token
        key: token
  - targetPath: "secureJsonData.tlsCACert"
    valueFrom:
      configMapKeyRef:
        name: ocp-injected-certs
        key: service-ca.crt
