apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true
  name: patch-console-kuadrant-plugin
  namespace: openshift-gitops
spec:
  template:
    metadata:
      name: patch-console-kuadrant-plugin
    spec:
      containers:
        - name: patch-console
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - '-c'
            - |
              set -e
              echo "Ensuring kuadrant-console-plugin is in Console plugins list..."
              if ! oc get console.operator.openshift.io cluster -o jsonpath='{.spec.plugins[*]}' | grep -qw "kuadrant-console-plugin"; then
                echo "Adding kuadrant-console-plugin to Console..."
                oc patch console.operator.openshift.io cluster --type=json -p='[{"op": "add", "path": "/spec/plugins/-", "value": "kuadrant-console-plugin"}]'
                echo "✅ Plugin kuadrant-console-plugin added."
              else
                echo "✅ Plugin kuadrant-console-plugin already present."
              fi
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      restartPolicy: Never
      serviceAccountName: openshift-gitops-argocd-application-controller
      tolerations:
        - key: node-role.kubernetes.io/infra
          operator: Exists
