apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: telemetry-manager
  namespace: openshift-ingress
rules:
- apiGroups:
  - telemetry.istio.io
  resources:
  - telemetries
  verbs:
  - '*'
