apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: granite-embedding-sa
  name: granite-embedding-sa-token
  namespace: ai-embedding-service
type: kubernetes.io/service-account-token
