apiVersion: ogx.io/v1beta1
kind: OGXServer
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: lsd-genai-playground
  labels:
    opendatahub.io/dashboard: "true"
  name: lsd-genai-playground
  namespace: ai-project-a
spec:
  distribution:
    name: rh
  network:
    port: 8321
  overrideConfig:
    key: config.yaml
    name: ogx-base-config
  workload:
    replicas: 1
    overrides:
      command:
      - /bin/sh
      - -c
      - ogx run /etc/ogx/config.yaml --insecure
      env:
      - name: PGVECTOR_HOST
        valueFrom:
          configMapKeyRef:
            key: PGVECTOR_HOST
            name: ogxserver-vector-connection
      - name: PGVECTOR_PORT
        valueFrom:
          configMapKeyRef:
            key: PGVECTOR_PORT
            name: ogxserver-vector-connection
      - name: PGVECTOR_DB
        valueFrom:
          configMapKeyRef:
            key: PGVECTOR_DB
            name: ogxserver-vector-connection
      - name: PGVECTOR_USER
        valueFrom:
          configMapKeyRef:
            key: PGVECTOR_USER
            name: ogxserver-vector-connection
      - name: PGVECTOR_PASSWORD
        valueFrom:
          secretKeyRef:
            key: PGVECTOR_PASSWORD
            name: ogxserver-vector-connection
      - name: POSTGRES_HOST
        valueFrom:
          configMapKeyRef:
            key: POSTGRES_HOST
            name: ogxserver-postgres-metadata
      - name: POSTGRES_PORT
        valueFrom:
          configMapKeyRef:
            key: POSTGRES_PORT
            name: ogxserver-postgres-metadata
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            key: POSTGRES_DB
            name: ogxserver-postgres-metadata
      - name: POSTGRES_USER
        valueFrom:
          configMapKeyRef:
            key: POSTGRES_USER
            name: ogxserver-postgres-metadata
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: POSTGRES_PASSWORD
            name: ogxserver-postgres-metadata
      - name: HF_HUB_OFFLINE
        value: "1"
      - name: TRANSFORMERS_OFFLINE
        value: "1"
      - name: HF_DATASETS_OFFLINE
        value: "1"
      - name: SENTENCE_TRANSFORMERS_HOME
        value: /opt/app-root/.cache/huggingface/hub
