apiVersion: v1
kind: ConfigMap
metadata:
  name: ogxserver-vector-connection
  namespace: ai-project-a
data:
  PGVECTOR_DB: ogxservervectordb
  PGVECTOR_HOST: postgresql.external-db-ogxserver-vector.svc.cluster.local
  PGVECTOR_PORT: "5432"
  PGVECTOR_USER: ogxservervector
