apiVersion: v1
kind: ConfigMap
metadata:
  name: ogxserver-postgres-metadata
  namespace: ai-project-a
data:
  POSTGRES_DB: ogxservermetadatadb
  POSTGRES_HOST: postgresql.external-db-ogxserver-metadata.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ogxservermetadata
