apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-registry-db-secret
  namespace: external-db-model-registry
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
