apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ai-project-a-cm-ingestion-code.yaml
- ai-project-a-cm-ogx-base-config.yaml
- ai-project-a-cm-ogxserver-postgres-metadata.yaml
- ai-project-a-cm-ogxserver-vector-connection.yaml
- ai-project-a-inferenceservice-qwen3-06b-100.yaml
- ai-project-a-job-aws-connection-mcg.yaml
- ai-project-a-job-model-ingest.yaml
- ai-project-a-obc-models.yaml
- ai-project-a-ogxserver-lsd-genai-playground.yaml
- ai-project-a-rb-aws-connection-mcg.yaml
- ai-project-a-role-aws-connection-mcg.yaml
- ai-project-a-sa-aws-connection-mcg.yaml
- ai-project-a-sa-model-ingestion.yaml
- ai-project-a-secret-ogxserver-postgres-metadata.yaml
- ai-project-a-secret-ogxserver-vector-connection.yaml
- ai-project-a-servingruntime-qwen3-06b-100.yaml
- cluster-namespace-ai-project-a.yaml
- rhoai-model-registries-modelregistry-model-registry.yaml
- rhoai-model-registries-networkpolicy-allow-ai-projects.yaml
- rhoai-model-registries-rb-model-ingest-job.yaml
- rhoai-model-registries-role-model-ingest-job.yaml
- rhoai-model-registries-secret-registry-db.yaml
