apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ai-project-a-obc-models.yaml
- ai-project-a-rb-aws-connection-mcg.yaml
- ai-project-a-role-aws-connection-mcg.yaml
- cluster-namespace-ai-project-a.yaml
- openshift-gitops-job-aws-connection-mcg.yaml
- openshift-gitops-sa-aws-connection-mcg.yaml
