apiVersion: v1
kind: Secret
metadata:
  annotations:
    security.internal/credential-type: demo-placeholder
  name: registry-db-secret
  namespace: rhoai-model-registries
stringData:
  database-password: changeme-demo-only
