apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-clusterqueue-cluster-queue-gpu.yaml
- cluster-namespace-gpu-users.yaml
- gpu-users-localqueue-local-queue-gpu.yaml
- redhat-ods-applications-hardwareprofile-profile-l40s-slice.yaml
