apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inferenceservice-user
  namespace: ai-generation-llm-rag
rules:
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  verbs:
  - get
  - list
