apiVersion: v1
kind: Secret
metadata:
  annotations:
    security.internal/credential-type: demo-placeholder
  name: pgvector-connection
  namespace: ai-generation-llm-rag
stringData:
  PGVECTOR_DB: ragdb
  PGVECTOR_HOST: rag-postgresql.external-db-ai-generation-llm-rag.svc.cluster.local
  PGVECTOR_PASSWORD: changeme-demo-only
  PGVECTOR_PORT: "5432"
  PGVECTOR_USER: raguser
