apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines
  namespace: ai-generation-llm-rag
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  database:
    externalDB:
      host: dspa-mariadb.external-db-generation-llm-rag.svc.cluster.local
      port: "3306"
      username: mlpipeline
      pipelineDBName: mlpipeline
      passwordSecret:
        name: dspa-mariadb-password
        key: password
  objectStorage:
    externalStorage:
      host: s3.openshift-storage.svc
      port: "443"
      bucket: "ai-generation-llm-rag-pipelines"
      scheme: https
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: pipeline-artifacts
  persistenceAgent:
    deploy: true
  scheduledWorkflow:
    deploy: true
