apiVersion: v1
kind: Service
metadata:
  name: rag-postgresql
  namespace: external-db-generation-llm-rag
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: rag-postgresql
  type: ClusterIP
