apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llamastack-postgresql
  namespace: external-db-ai-generation-llm-rag
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
