apiVersion: v1
data:
  tls.cnf: |
    [mysqld]
    ssl-ca=/etc/mysql-certs/tls.crt
    ssl-cert=/etc/mysql-certs/tls.crt
    ssl-key=/etc/mysql-certs/tls.key
kind: ConfigMap
metadata:
  name: dspa-mariadb-tls-config
  namespace: external-db-generation-llm-rag
