apiVersion: v1
kind: Service
metadata:
  annotations:
    # OpenShift Service CA will automatically create a TLS certificate
    service.beta.openshift.io/serving-cert-secret-name: dspa-mariadb-tls
  name: dspa-mariadb
  namespace: external-db-generation-llm-rag
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: dspa-mariadb
  type: ClusterIP
