apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dspa-mariadb
  namespace: external-uc-generation-llm-rag
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
