apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- ai-generation-llm-rag-cm-pipeline-rag-data-ingestion.yaml
- ai-generation-llm-rag-dspa-pipelines.yaml
- ai-generation-llm-rag-obc-pipeline-artifacts.yaml
- ai-generation-llm-rag-rb-pipeline-configmap-reader.yaml
- ai-generation-llm-rag-rb-pipeline-manager.yaml
- ai-generation-llm-rag-role-pipeline-configmap-reader.yaml
- ai-generation-llm-rag-secret-dspa-mariadb-password.yaml
- ai-generation-llm-rag-secret-rag-postgresql-credentials.yaml
- cluster-crb-argocd-manage-uc-workload.yaml
- cluster-namespace-ai-generation-llm-rag.yaml
- cluster-namespace-external-db-generation-llm-rag.yaml
- external-db-generation-llm-rag-configmap-dspa-mariadb-tls-config.yaml
- external-db-generation-llm-rag-deployment-dspa-mariadb.yaml
- external-db-llamastack-deployment-rag-postgresql.yaml
- external-db-generation-llm-rag-pvc-dspa-mariadb.yaml
- external-db-llamastack-pvc-rag-postgresql.yaml
- external-db-generation-llm-rag-secret-dspa-mariadb-credentials.yaml
- external-db-llamastack-secret-rag-postgresql-credentials.yaml
- external-db-generation-llm-rag-service-dspa-mariadb.yaml
- external-db-llamastack-service-rag-postgresql.yaml
- ai-generation-llm-rag-notebook-rag-ingestion.yaml
- openshift-gitops-cm-pipeline-upload-script.yaml
- openshift-gitops-job-upload-pipeline-rag-data-ingestion.yaml
- openshift-gitops-sa-pipeline-uploader.yaml
