apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- ai-generation-llm-rag-cm-ingestion-notebook.yaml
- ai-generation-llm-rag-cm-pipeline-rag-data-ingestion.yaml
- ai-generation-llm-rag-configmap-granite-chat-template.yaml
- ai-generation-llm-rag-dspa-pipelines.yaml
- ai-generation-llm-rag-inferenceservice-granite-embedding.yaml
- ai-generation-llm-rag-inferenceservice-granite-llm.yaml
- ai-generation-llm-rag-llamastackdistribution-llamastack.yaml
- ai-generation-llm-rag-notebook-rag-ingestion.yaml
- ai-generation-llm-rag-obc-pipeline-artifacts.yaml
- ai-generation-llm-rag-pvc-rag-ingestion-storage.yaml
- ai-generation-llm-rag-rb-allow-llamastack-access.yaml
- ai-generation-llm-rag-rb-pipeline-configmap-reader.yaml
- ai-generation-llm-rag-rb-pipeline-manager.yaml
- ai-generation-llm-rag-role-inferenceservice-user.yaml
- ai-generation-llm-rag-role-pipeline-configmap-reader.yaml
- ai-generation-llm-rag-sa-granite-embedding-sa.yaml
- ai-generation-llm-rag-sa-granite-llm-sa.yaml
- ai-generation-llm-rag-secret-dspa-mariadb-password.yaml
- ai-generation-llm-rag-secret-granite-embedding-sa-token.yaml
- ai-generation-llm-rag-secret-granite-llm-sa-token.yaml
- ai-generation-llm-rag-secret-pgvector-connection.yaml
- ai-generation-llm-rag-secret-postgres-secret.yaml
- ai-generation-llm-rag-secret-quay-redhat-ai-services.yaml
- ai-generation-llm-rag-secret-rag-postgresql-credentials.yaml
- ai-generation-llm-rag-secret-registry-redhat-io.yaml
- ai-generation-llm-rag-servingruntime-granite-embedding.yaml
- ai-generation-llm-rag-servingruntime-granite-llm.yaml
- cluster-crb-argocd-manage-uc-workload.yaml
- cluster-namespace-ai-generation-llm-rag.yaml
- cluster-namespace-external-db-ai-generation-llm-rag.yaml
- external-db-ai-generation-llm-rag-configmap-dspa-mariadb-tls-config.yaml
- external-db-ai-generation-llm-rag-deployment-dspa-mariadb.yaml
- external-db-ai-generation-llm-rag-deployment-llamastack-postgresql.yaml
- external-db-ai-generation-llm-rag-deployment-rag-postgresql.yaml
- external-db-ai-generation-llm-rag-pvc-dspa-mariadb.yaml
- external-db-ai-generation-llm-rag-pvc-llamastack-postgresql.yaml
- external-db-ai-generation-llm-rag-pvc-rag-postgresql.yaml
- external-db-ai-generation-llm-rag-secret-dspa-mariadb-credentials.yaml
- external-db-ai-generation-llm-rag-secret-llamastack-postgresql-credentials.yaml
- external-db-ai-generation-llm-rag-secret-rag-postgresql-credentials.yaml
- external-db-ai-generation-llm-rag-service-dspa-mariadb.yaml
- external-db-ai-generation-llm-rag-service-llamastack-postgresql.yaml
- external-db-ai-generation-llm-rag-service-rag-postgresql.yaml
- openshift-gitops-cm-pipeline-upload-script.yaml
- openshift-gitops-job-upload-pipeline-rag-data-ingestion.yaml
- openshift-gitops-sa-pipeline-uploader.yaml
- redhat-ods-applications-cm-llamastack-embedding-provider.yaml
- redhat-ods-applications-rb-llamastack-use-scc.yaml
