apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
  name: demo-ei
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /metadata/annotations
    kind: ConfigMap
    name: cluster-versions
  project: demo-ei
  source:
    path: components/demo-ei/overlays/default
    repoURL: https://github.com/lautou/ocp-open-env-install-tool.git
    targetRevision: demo-ei
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
