apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uc-ai-generation-llm-rag
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: ai-usecases
  source:
    path: components/uc-ai-generation-llm-rag/overlays/default
    repoURL: https://github.com/lautou/ocp-open-env-install-tool.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
  ignoreDifferences:
  - group:
    jsonPointers:
    - /metadata/annotations
    kind: ConfigMap
    name: cluster-versions
  - group: kubeflow.org
    jsonPointers:
    - /spec/template/spec/containers/1/image
    kind: Notebook
    name: rag-ingestion
