apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "key":
      "node-role.kubernetes.io/infra"}]
  name: openshift-logging
  labels:
    openshift.io/cluster-monitoring: "true"
    openshift.io/cluster-logging: "true"
