apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: mistral-medium-3-5-bf16
  namespace: demo-ei
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: gp3-csi
