apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    openshift.io/display-name: lsd-genai-playground
  labels:
    opendatahub.io/dashboard: "true"
  name: lsd-genai-playground
  namespace: demo-ei
spec:
  network:
    allowedFrom:
      namespaces:
      - demo-ei
    exposeRoute: false
  replicas: 1
  server:
    distribution:
      name: rh
    containerSpec:
      command:
      - /bin/sh
      - -c
      - llama stack run /etc/llama-stack/config.yaml
      env:
      - name: VLLM_TLS_VERIFY
        value: "false"
      - name: MILVUS_DB_PATH
        value: ~/.llama/milvus.db
      - name: FMS_ORCHESTRATOR_URL
        value: http://localhost
      - name: VLLM_MAX_TOKENS
        value: "4096"
      - name: VLLM_API_TOKEN_1
        value: fake
      - name: LLAMA_STACK_CONFIG_DIR
        value: /opt/app-root/src/.llama/distributions/rh/
      name: llama-stack
      port: 8321
      resources:
        limits:
          cpu: "2"
          memory: 12Gi
        requests:
          cpu: 250m
          memory: 500Mi
