apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-namespace-demo-ei.yaml
- demo-ei-inferenceservice-mistral-medium-3-5.yaml
- demo-ei-pvc-mistral-medium-3-5-bf16.yaml
- demo-ei-secret-mistral-medium-3-5-storage.yaml
- demo-ei-servingruntime-mistral-medium-3-5.yaml
