apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: klusterlet
spec:
  nodePlacement:
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
