kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-klusterlet
rules:
  - verbs:
      - '*'
    apiGroups:
      - operator.open-cluster-management.io
    resources:
      - klusterlets
