apiVersion: v1
kind: Secret
metadata:
  labels:
    app: klusterlet
  name: open-cluster-management-image-pull-credentials
  namespace: open-cluster-management-agent
data:
  .dockerconfigjson: e30=
type: kubernetes.io/dockerconfigjson