apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: team-b-queue
  namespace: ai-team-b
spec:
  clusterQueue: shared-cluster-queue
