apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ai-team-a-localqueue-team-a-queue.yaml
- ai-team-b-localqueue-team-b-queue.yaml
- cluster-clusterqueue-shared-cluster-queue.yaml
