apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-cr-secrets-unsealer.yaml
  - kube-system-rb-edit-openshift-gitops-openshift-gitops-argocd-application-controller.yaml 
