apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/clusterName
      value: secured-ocp
  target:
    kind: SecuredCluster
    name: stackrox-secured-cluster-services
